[package]
name = "bevy_birdsong"
version = "0.1.0-dev"
edition = "2021"
description = "A dialogue box manager for the Bevy Game Engine"
repository = "https://github.com/jlvoiseux/bevy_birdsong"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bevy = "0.8.1"
